/*!
 * mmplayer.js - version 0.0.1
 * is Middle Media Player.
 * http://github.com/nenjiru/mmplayer.js
 * 
 * Build on 2013-02-12 20:20
 * Copyright (C) 2013, Minoru Nakanou
 * Licensed under the MIT License.
 */
(function(e){"use strict";e.cmn=e.cmn||{},e.cmn.event=e.cmn.event||{};var t=function(e,t,n){this.target=e,this.type=t,this.data=n},n=function(){var e={};this.addEventListener=function(t,n){(e[t]||(e[t]=[])).push(n)},this.hasEventListener=function(t){return!!e[t]},this.removeEventListener=function(t,n){var r=e[t];if(r)for(var i=r.length-1;i>=0;i--)r[i]===n&&r.splice(i,1)},this.onesEventListener=function(e,t){var n=this,r=function(i){n.removeEventListener(e,r),t.apply(n,[i]),r=null};this.addEventListener(e,r)},this.dispatchEvent=function(n,r){var i=e[n],s=new t(this,n,r);if(i){i=i.concat();for(var o=0,u=i.length;o<u;o++)i[o].apply(this,[s])}}};e.cmn.event.EventDispatcher=n})(this),function(e){"use strict";function r(e,t){var n=[],r=e.split("/"),i=r[r.length-1],s=i.split(".")[1],o=i.match(/\d+/)[0],u=-o.length;r.pop(),r=r.join("/");for(var a=1,f=t+1,l;a<f;a++)o.length>1?l=(o+a).slice(u):l=String(a),n.push(r+"/"+l+"."+s);return n}function i(e,t){return function(){return e.apply(t,arguments)}}e.cmn=e.cmn||{},e.cmn.display=e.cmn.display||{};var t=e.cmn.event.EventDispatcher,n=function(e,s,o,u,a){function c(){this.stop(),this.dispatchEvent(n.ENDED)}t.apply(this);var f=null,l=0;this.frame=[],this.play=function(){if(f===null&&this.frame.length>100){var t=this,r=t.frame,i=e.getContext("2d"),u=e.width,c=e.height,h,p,d;t.dispatchEvent(n.START),f=setInterval(function(){h=s.currentTime,l===h?(t.stop(),t.dispatchEvent(n.PAUSE)):(d=~~(h/o*a),p=r[d],p.width&&p.height&&i.drawImage(p,0,0,u,c),t.currentFrame=d,t.dispatchEvent(n.UPDATE,d)),l=h},1e3/n.FPS)}},this.stop=function(){clearInterval(f),f=null},this.load=function(){var e=this,t,i=e.frame,s=r(u,a);t=setInterval(function(){var r=new Image;r.src=s.shift(),i.push(r),r.onload=function(t){r.onload=null,e.dispatchEvent(n.PROGRESS,i.length),i.length>=a&&e.dispatchEvent(n.COMPLETE,i)},s.length===0&&clearInterval(t)},25)},s.addEventListener("ended",i(c,this)),s.addEventListener("timeupdate",i(this.play,this))};n.FPS=30,n.PROGRESS="mmplayer_progress",n.COMPLETE="mmplayer_complete",n.UPDATE="mmplayer_update",n.START="mmplayer_start",n.PAUSE="mmplayer_pause",n.ENDED="mmplayer_ended",e.cmn.display.MiddleMediaPlayer=n,e.mmplayer=n}(this);